kind: ConfigMap
apiVersion: v1
metadata:
  name: config
  namespace: system
data:
  config: |
    job:
      AutoDelTime: 30
      BackLimit: 5
      Image: kubespheredev/kubeeye:latest
      ImagePullPolicy: Always
