apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: kubeeye-controller-manager
  name: {{ include "charts.fullname" . }}-controller-manager
  namespace: {{ .Release.Namespace}}
spec:
  replicas: {{ .Values.replicaCount}}
  selector:
    matchLabels:
      control-plane: {{ include "charts.fullname" . }}-controller-manager
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: {{ include "charts.fullname" . }}-controller-manager
    spec:
      containers:
        - args:
            - --secure-listen-address=0.0.0.0:8443
            - --upstream=http://127.0.0.1:8080/
            - --logtostderr=true
            - --v=0
          image: {{ .Values.image.rbac.repository}}:{{ .Values.image.rbac.tag}}
          imagePullPolicy: {{ .Values.image.rbac.pullPolicy}}
          name: kube-rbac-proxy
          ports:
            - containerPort: 8443
              name: https
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 5m
              memory: 64Mi
        - args:
            - --health-probe-bind-address=:8081
            - --metrics-bind-address=127.0.0.1:8080
            - --leader-elect
          image: {{ .Values.image.controller.repository}}:{{ .Values.image.controller.tag}}
          imagePullPolicy: {{.Values.image.controller.pullPolicy}}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          name: manager
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources: {{ toYaml .Values.resources | nindent 12}}
          securityContext:
            allowPrivilegeEscalation: false
      securityContext:
        runAsNonRoot: true
      serviceAccountName: kubeeye-controller-manager
      terminationGracePeriodSeconds: 10
