apiVersion: v1
data:
  config: |
    job:
      AutoDelTime: 30
      BackLimit: 5
      Image: kubespheredev/kubeeye-job:v1.0.0-alpha.1
      ImagePullPolicy: Always
kind: ConfigMap
metadata:
  name: kubeeye-config
  namespace: kubeeye-system