apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "charts.fullname" . }}-leader-election-rolebinding
  namespace: {{ .Release.Namespace}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "charts.fullname" . }}-leader-election-role
subjects:
  - kind: ServiceAccount
    name: {{ include "charts.fullname" . }}-controller-manager
    namespace: {{ .Release.Namespace}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "charts.fullname" . }}-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "charts.fullname" . }}-manager-role
subjects:
  - kind: ServiceAccount
    name: {{ include "charts.fullname" . }}-controller-manager
    namespace: {{ .Release.Namespace}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "charts.fullname" . }}-proxy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "charts.fullname" . }}-proxy-role
subjects:
  - kind: ServiceAccount
    name: {{ include "charts.fullname" . }}-controller-manager
    namespace: {{ .Release.Namespace}}