apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: {{ include "charts.fullname" . }}-controller-manager
  name: {{ include "charts.fullname" . }}-controller-manager-metrics-service
  namespace: {{ .Release.Namespace}}
spec:
  ports:
    - name: https
      port: 8443
      protocol: TCP
      targetPort: https
  selector:
    control-plane: {{ include "charts.fullname" . }}-controller-manager