apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: kubeeye-controller-manager
  name: kubeeye-controller-manager-metrics-service
  namespace: kubeeye-system
spec:
  ports:
    - name: https
      port: 8443
      protocol: TCP
      targetPort: https
  selector:
    control-plane: kubeeye-controller-manager