# permissions for end users to view audittasks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: audittask-viewer-role
rules:
- apiGroups:
  - kubeeye.kubesphere.io
  resources:
  - audittasks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kubeeye.kubesphere.io
  resources:
  - audittasks/status
  verbs:
  - get
