# permissions for end users to edit auditplans.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: auditplan-editor-role
rules:
- apiGroups:
  - kubeeye.kubesphere.io
  resources:
  - auditplans
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubeeye.kubesphere.io
  resources:
  - auditplans/status
  verbs:
  - get
