# permissions for end users to view auditplans.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: auditplan-viewer-role
rules:
- apiGroups:
  - kubeeye.kubesphere.io
  resources:
  - auditplans
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kubeeye.kubesphere.io
  resources:
  - auditplans/status
  verbs:
  - get
