apiVersion: kubeeye.kubesphere.io/v1alpha2
kind: AuditPlan
metadata:
  name: auditplan-sample
spec:
  # TODO(user): Add fields here
  auditors:
    - kubeeye
  #    - kubebench
  schedule: "@every 20m"
  timeout: "4m"
