apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kubeeye.fullname" . }}-config
  labels:
  {{- include "kubeeye.labels" . | nindent 4 }}
data:
  config: {{ .Values.config.config | toYaml | indent 1 }}