apiVersion: kubeeye.kubesphere.io/v1alpha2
kind: InspectPlan
metadata:
  name: inspectplan-sample
  namespace: kubeeye-system
spec:
  schedule: "*/3 * * *  ?"
  maxTasks: 10
  auditors:
    - kubeeye
  tag: kubeeye_workloads_rego
