# Description: The rules for inspecting systemd services.
---
apiVersion: kubeeye.kubesphere.io/v1alpha2
kind: InspectRule
metadata:
  name: inspect-rule-systemd
spec:
  systemd:
    - name: docker
      rule: docker == "active"
    - name: etcd
      rule: etcd == "active"
    - name: kubelet
      rule: kubelet == "active"
