# Description: The rules for inspecting Pod resources.
---
apiVersion: kubeeye.kubesphere.io/v1alpha2
kind: InspectRule
metadata:
  name: pod-inspect-rules
spec:
  opas:
  - name: imagePullPolicyRuleForPod
    rule: |-
      package inspect.kubeeye
      import rego.v1
      
      excluded_namespaces := {
           "kube-system",
           "argocd",
           "kubeeye-system",
           "kubesphere-system",
           "kubesphere-monitoring-system",
           "kubesphere-controls-system",
           "kubesphere-logging-system",
           "kubesphere-devops-system"

      }
      deny contains msg if {
  
          input.kind == "Pod"
          input.apiVersion == "v1"
          
          not excluded_namespaces[input.metadata.namespace]
          
          level := "WARNING"
          
          not input.metadata.ownerReferences
          container := input.spec.containers[_]
          container.imagePullPolicy != "IfNotPresent"
  
          msg := {
              "Name": sprintf("%v", [input.metadata.name]),
              "Namespace": sprintf("%v", [input.metadata.namespace]),
              "Type": sprintf("%v", [input.kind]),
              "Message": "PodImagePullPolicyRule",
              "Reason": sprintf("当前资源镜像拉取策略为: %v , 需要修改为IfNotPresent", [container.imagePullPolicy]),
              "Level": sprintf("%v", [level])
          }
      }

  - name: readinessProbeRuleForPod
    rule: |-
      package inspect.kubeeye
      import rego.v1
      excluded_namespaces := {
           "kube-system",
           "argocd",
           "kubeeye-system",
           "kubesphere-system",
           "kubesphere-monitoring-system",
           "kubesphere-controls-system",
           "kubesphere-logging-system",
           "kubesphere-devops-system"

      }
      deny contains msg if {
          
        input.kind == "Pod"
        input.apiVersion == "v1"
        not excluded_namespaces[input.metadata.namespace]
        level := "WARNING"
        
        not input.metadata.ownerReferences

        container := input.spec.containers[_]
        not container.readinessProbe

        msg := {
            "Name": sprintf("%v", [input.metadata.name]),
            "Namespace": sprintf("%v", [input.metadata.namespace]),
            "Type": sprintf("%v", [input.kind]),
            "Message": "PodReadinessProbeRule",
            "Reason": "当前资源没有配置就绪探针",
            "Level": sprintf("%v", [level])
        }
      }


  - name: livenessProbeRuleForPod
    rule: |-
      package inspect.kubeeye
      import rego.v1
      excluded_namespaces := {
           "kube-system",
           "argocd",
           "kubeeye-system",
           "kubesphere-system",
           "kubesphere-monitoring-system",
           "kubesphere-controls-system",
           "kubesphere-logging-system",
           "kubesphere-devops-system"

      }
      deny contains msg if {
        input.kind == "Pod"
        input.apiVersion == "v1"
        not excluded_namespaces[input.metadata.namespace]
        level := "WARNING"
        
        not input.metadata.ownerReferences

        container := input.spec.containers[_]
        not container.livenessProbe

        msg := {
            "Name": sprintf("%v", [input.metadata.name]),
            "Namespace": sprintf("%v", [input.metadata.namespace]),
            "Type": sprintf("%v", [input.kind]),
            "Message": "PodLivenessProbeRule",
            "Reason": "当前资源没有配置存活探针",
            "Level": sprintf("%v", [level])
        }
      }

  - name: hostPathRuleForPod
    rule: |-
      package inspect.kubeeye
      import rego.v1
      excluded_namespaces := {
           "kube-system",
           "argocd",
           "kubeeye-system",
           "kubesphere-system",
           "kubesphere-monitoring-system",
           "kubesphere-controls-system",
           "kubesphere-logging-system",
           "kubesphere-devops-system"

      }
      deny contains msg if {

        input.kind == "Pod"
        input.apiVersion == "v1"
        not excluded_namespaces[input.metadata.namespace]
        level := "DANGER"

        not input.metadata.ownerReferences

        container := input.spec.containers[_]

        volume := input.spec.volumes[_]

        "hostPath" in volume

        volume_mount := container.volumeMounts[_]

        volume_mount.name == volume.name
        not volume_mount.readOnly

        msg := {
            "Name": sprintf("%v", [input.metadata.name]),
            "Namespace": sprintf("%v", [input.metadata.namespace]),
            "Type": sprintf("%v", [input.kind]),
            "Message": "PodHostPathRule",
            "Reason": sprintf("当前资源使用hostPath挂载卷 , 卷名: %v , 未配置只读模式", [volume.name]),
            "Level": sprintf("%v", [level])
        }
      }

  - name: privilegedRuleForPod
    rule: |-
      package inspect.kubeeye
      import rego.v1
      excluded_namespaces := {
           "kube-system",
           "argocd",
           "kubeeye-system",
           "kubesphere-system",
           "kubesphere-monitoring-system",
           "kubesphere-controls-system",
           "kubesphere-logging-system",
           "kubesphere-devops-system"

      }
      deny contains msg if {
        
        input.kind == "Pod"
        input.apiVersion == "v1"
        not excluded_namespaces[input.metadata.namespace]
        level := "DANGER"
        
        not input.metadata.ownerReferences
        
        input.spec.containers[_].securityContext.privileged == true

        msg := {
            "Name": sprintf("%v", [input.metadata.name]),
            "Namespace": sprintf("%v", [input.metadata.namespace]),
            "Type": sprintf("%v", [input.kind]),
            "Message": "PodPrivilegedRule",
            "Reason": "当前资源已启用特权模式",
            "Level": sprintf("%v", [level])
        }
      }

  - name: insecureCapabilitiesRuleForPod
    rule: |-
      package inspect.kubeeye
      import rego.v1
      excluded_namespaces := {
           "kube-system",
           "argocd",
           "kubeeye-system",
           "kubesphere-system",
           "kubesphere-monitoring-system",
           "kubesphere-controls-system",
           "kubesphere-logging-system",
           "kubesphere-devops-system"

      }
      deny contains msg if {
        
        input.kind == "Pod"
        input.apiVersion == "v1"
        not excluded_namespaces[input.metadata.namespace]
        level := "CRITICAL"
        
        not input.metadata.ownerReferences

        insecureCapabilities := ["CHOWN", "DAC_OVERRIDE", "FSETID", "FOWNER", "MKNOD", "NET_RAW", "SETGID", "SETUID", "SETFCAP", "NET_BIND_SERVICE","SYS_CHROOT","KILL","AUDIT_WRITE"]
        container := input.spec.containers[_]
        capabilities := container.securityContext.capabilities.add[_]
        insecureCapabilities[_] == capabilities

        msg := {
            "Name": sprintf("%v", [input.metadata.name]),
            "Namespace": sprintf("%v", [input.metadata.namespace]),
            "Type": sprintf("%v", [input.kind]),
            "Message": "PodInsecureCapabilitiesRule",
            "Reason": sprintf("容器 '%v' 配置了系统权限: %v", [container.name, capabilities]),
            "Level": sprintf("%v", [level])
        }
      }

  - name: highRiskCapabilitiesRuleForPod
    rule: |-
      package inspect.kubeeye
      import rego.v1
      excluded_namespaces := {
           "kube-system",
           "argocd",
           "kubeeye-system",
           "kubesphere-system",
           "kubesphere-monitoring-system",
           "kubesphere-controls-system",
           "kubesphere-logging-system",
           "kubesphere-devops-system"

      }
      deny contains msg if {
        
        input.kind == "Pod"
        input.apiVersion == "v1"
        not excluded_namespaces[input.metadata.namespace]
        level := "DANGER"  
        
        not input.metadata.ownerReferences
        
        HighRiskCapabilities := ["NET_ADMIN", "SYS_ADMIN", "ALL"]
        container := input.spec.containers[_]
        capabilities := container.securityContext.capabilities.add[_]
        HighRiskCapabilities[_] == capabilities

        msg := {
            "Name": sprintf("%v", [input.metadata.name]),
            "Namespace": sprintf("%v", [input.metadata.namespace]),
            "Type": sprintf("%v", [input.kind]),
            "Message": "PodHighRiskCapabilitiesRule",
            "Reason": sprintf("容器 '%v' 配置了系统权限: %v", [container.name, capabilities]),
            "Level": sprintf("%v", [level])
        }
      }

  - name: cpuRequestsRuleForPod
    rule: |-
      package inspect.kubeeye
      import rego.v1
      excluded_namespaces := {
           "kube-system",
           "argocd",
           "kubeeye-system",
           "kubesphere-system",
           "kubesphere-monitoring-system",
           "kubesphere-controls-system",
           "kubesphere-logging-system",
           "kubesphere-devops-system"

      }
      deny contains msg if {

        input.kind == "Pod"
        input.apiVersion == "v1"
        not excluded_namespaces[input.metadata.namespace]       
        level := "WARNING"
        
        not input.metadata.ownerReferences

        container := input.spec.containers[_]
        not container.resources.requests.cpu

        msg := {
            "Name": sprintf("%v", [input.metadata.name]),
            "Namespace": sprintf("%v", [input.metadata.namespace]),
            "Type": sprintf("%v", [input.kind]), 
            "Message": "PodCPURequestsRule",
            "Reason": sprintf("容器 '%v' 未配置CPU资源请求", [container.name]),
            "Level": sprintf("%v", [level])
        }
      }

  - name: cpuLimitsRuleForPod
    rule: |-
      package inspect.kubeeye
      import rego.v1
      excluded_namespaces := {
           "kube-system",
           "argocd",
           "kubeeye-system",
           "kubesphere-system",
           "kubesphere-monitoring-system",
           "kubesphere-controls-system",
           "kubesphere-logging-system",
           "kubesphere-devops-system"

      }
      deny contains msg if {
        
        input.kind == "Pod"
        input.apiVersion == "v1"
        not excluded_namespaces[input.metadata.namespace]
        level := "WARNING"
        
        not input.metadata.ownerReferences

        container := input.spec.containers[_]
        not container.resources.limits.cpu

        msg := {
            "Name": sprintf("%v", [input.metadata.name]),
            "Namespace": sprintf("%v", [input.metadata.namespace]),
            "Type": sprintf("%v", [input.kind]),
            "Message": "PodCPULimitsRule",
            "Reason": sprintf("容器 '%v' 未配置CPU资源限制", [container.name]),
            "Level": sprintf("%v", [level])
        }
      }

  - name: memoryRequestsRuleForPod
    rule: |-
      package inspect.kubeeye
      import rego.v1
      excluded_namespaces := {
           "kube-system",
           "argocd",
           "kubeeye-system",
           "kubesphere-system",
           "kubesphere-monitoring-system",
           "kubesphere-controls-system",
           "kubesphere-logging-system",
           "kubesphere-devops-system"

      }
      deny contains msg if {
        
        input.kind == "Pod"
        input.apiVersion == "v1"
        not excluded_namespaces[input.metadata.namespace]
        level := "WARNING"
        
        not input.metadata.ownerReferences

        container := input.spec.containers[_]
        not container.resources.requests.memory

        msg := {
            "Name": sprintf("%v", [input.metadata.name]),
            "Namespace": sprintf("%v", [input.metadata.namespace]),
            "Type": sprintf("%v", [input.kind]),
            "Message": "PodMemoryRequestsRule",
            "Reason": sprintf("容器 '%v' 未配置内存资源请求", [container.name]),
            "Level": sprintf("%v", [level])
        }
      }

  - name: memoryLimitsRuleForPod
    rule: |-
      package inspect.kubeeye
      import rego.v1
      excluded_namespaces := {
           "kube-system",
           "argocd",
           "kubeeye-system",
           "kubesphere-system",
           "kubesphere-monitoring-system",
           "kubesphere-controls-system",
           "kubesphere-logging-system",
           "kubesphere-devops-system"

      }
      deny contains msg if {

        input.kind == "Pod"
        input.apiVersion == "v1"
        not excluded_namespaces[input.metadata.namespace]
        level := "WARNING"
        
        not input.metadata.ownerReferences

        container := input.spec.containers[_]
        not container.resources.limits.memory

        msg := {
            "Name": sprintf("%v", [input.metadata.name]),
            "Namespace": sprintf("%v", [input.metadata.namespace]),
            "Type": sprintf("%v", [input.kind]),
            "Message": "PodMemoryLimitsRule",
            "Reason": sprintf("容器 '%v' 未配置内存资源限制", [container.name]),
            "Level": sprintf("%v", [level])
        }
      }

  - name: hostPortRuleForPod
    rule: |-
      package inspect.kubeeye
      import rego.v1
      excluded_namespaces := {
           "kube-system",
           "argocd",
           "kubeeye-system",
           "kubesphere-system",
           "kubesphere-monitoring-system",
           "kubesphere-controls-system",
           "kubesphere-logging-system",
           "kubesphere-devops-system"

      }
      deny contains msg if {
        
        input.kind == "Pod"
        input.apiVersion == "v1"
        not excluded_namespaces[input.metadata.namespace]
        level := "CRITICAL"

        not input.metadata.ownerReferences
          
        container := input.spec.containers[_]
        port := container.ports[_]
        port.hostPort

        msg := {
            "Name": sprintf("%v", [input.metadata.name]),
            "Namespace": sprintf("%v", [input.metadata.namespace]),
            "Type": sprintf("%v", [input.kind]),
            "Message": "PodHostPortRule",
            "Reason": sprintf("容器 '%v' 使用了 hostPort: %v", [container.name, port.hostPort]),
            "Level": sprintf("%v", [level])
        }
      }

  - name: hostPIDRuleForPod
    rule: |-
      package inspect.kubeeye
      import rego.v1
      excluded_namespaces := {
           "kube-system",
           "argocd",
           "kubeeye-system",
           "kubesphere-system",
           "kubesphere-monitoring-system",
           "kubesphere-controls-system",
           "kubesphere-logging-system",
           "kubesphere-devops-system"

      }
      deny contains msg if {
        
        input.kind == "Pod"
        input.apiVersion == "v1"
        not excluded_namespaces[input.metadata.namespace]
        level := "CRITICAL"
        not input.metadata.ownerReferences

        input.spec.hostPID == true

        msg := {
            "Name": sprintf("%v", [input.metadata.name]),
            "Namespace": sprintf("%v", [input.metadata.namespace]),
            "Type": sprintf("%v", [input.kind]),
            "Message": "PodHostPIDRule",
            "Reason": "当前资源已启用 hostPID",
            "Level": sprintf("%v", [level])
        }
      }

  - name: hostNetworkRuleForPod
    rule: |-
      package inspect.kubeeye
      import rego.v1
      excluded_namespaces := {
           "kube-system",
           "argocd",
           "kubeeye-system",
           "kubesphere-system",
           "kubesphere-monitoring-system",
           "kubesphere-controls-system",
           "kubesphere-logging-system",
           "kubesphere-devops-system"

      }
      deny contains msg if {
        
        input.kind == "Pod"
        input.apiVersion == "v1"
        not excluded_namespaces[input.metadata.namespace]
        level := "CRITICAL"
        
        not input.metadata.ownerReferences

        input.spec.hostNetwork == true

        msg := {
            "Name": sprintf("%v", [input.metadata.name]),
            "Namespace": sprintf("%v", [input.metadata.namespace]),
            "Type": sprintf("%v", [input.kind]),
            "Message": "PodHostNetworkRule",
            "Reason": "当前资源已启用 hostNetwork",
            "Level": sprintf("%v", [level])
        }
      }

  - name: hostIPCRuleForPod
    rule: |-
      package inspect.kubeeye
      import rego.v1
      excluded_namespaces := {
           "kube-system",
           "argocd",
           "kubeeye-system",
           "kubesphere-system",
           "kubesphere-monitoring-system",
           "kubesphere-controls-system",
           "kubesphere-logging-system",
           "kubesphere-devops-system"

      }
      deny contains msg if {
        
        input.kind == "Pod"
        input.apiVersion == "v1"
        not excluded_namespaces[input.metadata.namespace]
        level := "CRITICAL"
        not input.metadata.ownerReferences

        input.spec.hostIPC == true

        msg := {
            "Name": sprintf("%v", [input.metadata.name]),
            "Namespace": sprintf("%v", [input.metadata.namespace]),
            "Type": sprintf("%v", [input.kind]),
            "Message": "PodHostIPCRule",
            "Reason": "当前资源已启用 hostIPC",
            "Level": sprintf("%v", [level])
        }
      }

  - name: LivenessProbeTimeRuleForPod
    rule: |-
      package inspect.kubeeye
      import rego.v1
      excluded_namespaces := {
           "kube-system",
           "argocd",
           "kubeeye-system",
           "kubesphere-system",
           "kubesphere-monitoring-system",
           "kubesphere-controls-system",
           "kubesphere-logging-system",
           "kubesphere-devops-system"

      }
      deny contains msg if {
        
        input.kind == "Pod"
        input.apiVersion == "v1"
        not excluded_namespaces[input.metadata.namespace]
        level := "WARNING"
        
        not input.metadata.ownerReferences
        
        namespace_check(input.metadata.namespace)

        # 查找违规的容器，判断探测总时间大于180s的
        container := input.spec.containers[_]
        probe := container.livenessProbe
        
        initial_delay := object.get(probe, "initialDelaySeconds", 0)
        period := object.get(probe, "periodSeconds", 10)
        failure_threshold := object.get(probe, "failureThreshold", 3)
        total_time := initial_delay + (failure_threshold * period)

        total_time >= 180

        msg := {
            "Name": sprintf("%v", [input.metadata.name]),
            "Namespace": sprintf("%v", [input.metadata.namespace]),
            "Type": sprintf("%v", [input.kind]),
            "Message": "PodLivenessProbeTimeRule",
            "Reason": sprintf("容器 %v 存活探针探测总时间 >= 180s", [container.name]),
            "Level": sprintf("%v", [level])
        }
      }

      namespace_check(namespace) if {
          startswith(namespace, "kubesphere-")
      }
      namespace_check(namespace) if {
          namespace == "kube-system"
      }
