# Example: CheckConfigmap
# Description: Check if the subnet is used by multiple namespaces in the HostNic configuration.
---
apiVersion: kubeeye.kubesphere.io/v1alpha2
kind: InspectRule
metadata:
  name: configmap-inspect-rules
spec:
  opas:
  - name: CheckDuplicateSubnets
    rule: |-
      package inspect.kubeeye
      import rego.v1

      deny contains msg if {
        input.kind == "ConfigMap"
        input.apiVersion == "v1"
        
        input.metadata.namespace == "kube-system"
        input.metadata.name == "ipam-config"
      
        input.data.ipam != ""
        ipam_config := json.unmarshal(input.data.ipam)

        some ns, subnets in ipam_config
        some subnet in subnets

        usage := {
          "subnet": subnet,
          "namespaces": [ns |
              some other_ns, other_subnets in ipam_config
              some other_subnet in other_subnets
              other_subnet == subnet
              ns := other_ns
          ],
        }

        count(usage.namespaces) > 1

        level := "danger"
        msg := {
          "Name": sprintf("%v", [input.metadata.name]),
          "Namespace": sprintf("%v", [input.metadata.namespace]),
          "Type": sprintf("%v", [input.kind]),
          "Level": sprintf("%v", [level]),
          "Message": sprintf("subnet %v is used multi namespaces %v", [usage.subnet, usage.namespaces]),
          "Reason": "HostNic 配置中 subnet 被重复分配"
        }
      }
