# Description: Filter the file content by the specified rule.
---
apiVersion: kubeeye.kubesphere.io/v1alpha2
kind: InspectRule
metadata:
  name: inspect-rule-filter-file
spec:
  fileFilter:
    - name: systemLog
      path: /var/log/syslog
      rule: error
