name: Release

on:
  push:
    tags:
      - 'v*'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}


      - name: Build Job and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: build/job/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: kubespheredev/kubeeye-job:${{ github.ref_name }}
      - name: Build Controller and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: build/controller/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: kubespheredev/kubeeye-controller:${{ github.ref_name }}
      - name: Build ApiServer and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: build/apiserver/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: kubespheredev/kubeeye-apiserver:${{ github.ref_name }}

        
